<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.dempsay.agenthub</groupId>
    <artifactId>agent-hub</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>agent-hub-store</artifactId>
  <packaging>jar</packaging>

  <properties>
    <felix.bundle.exportcontents>org.dempsay.agenthub.store,org.dempsay.agenthub.store.*</felix.bundle.exportcontents>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.dempsay.agenthub</groupId>
      <artifactId>agent-hub-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.dempsay.aether</groupId>
      <artifactId>aether-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.dempsay.aether</groupId>
      <artifactId>aether-store-memory</artifactId>
    </dependency>
    <dependency>
      <groupId>org.dempsay.aether</groupId>
      <artifactId>aether-store-fs</artifactId>
    </dependency>
    <dependency>
      <groupId>org.dempsay.aether</groupId>
      <artifactId>aether-store-gen</artifactId>
      <optional>true</optional>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.dempsay.aether</groupId>
              <artifactId>aether-store-gen</artifactId>
              <version>${aether.version}</version>
            </path>
            <path>
              <groupId>org.dempsay.aether</groupId>
              <artifactId>aether-api</artifactId>
              <version>${aether.version}</version>
            </path>
            <path>
              <groupId>org.dempsay.utils</groupId>
              <artifactId>exceptional</artifactId>
              <version>${exceptional.version}</version>
            </path>
            <path>
              <groupId>org.freemarker</groupId>
              <artifactId>freemarker</artifactId>
              <version>${freemarker.version}</version>
            </path>
            <path>
              <groupId>org.dempsay.support.jsr269</groupId>
              <artifactId>jsr269-utilities</artifactId>
              <version>${jsr269-utilities.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
